# Generated by Django 3.1.1 on 2020-10-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetFinder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
